import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Kamalaya',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <body className="{inter.className}">
        <Sidebar />
        {children}
      </body>
    </html>
  );
}

// https://www.youtube.com/watch?v=KpGZjrrS3pY
