
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import Provider from '../Provider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata = {
//   title: 'Kamalaya',
//   description: 'Generated by create next app',
// };

export default function Layout({ children, session }) {
  return (
   
        <body>
          <Sidebar />
          {children}
        </body>
   
  );
}

// https://www.youtube.com/watch?v=KpGZjrrS3pY
